prog: main.o settab.o entab.o tabpos.o
	gcc -o prog main.o settab.o entab.o tabpos.o

main.o: main.c
	gcc -c main.c

settab.o: settab.c
	gcc -c settab.c

entab.o: entab.c
	gcc -c entab.c

tabpos.o: tabpos.c
	gcc -c tabpos.c