prog: main.o getop.o stack.o getch.o
	gcc -o prog main.o getop.o stack.o getch.o

main.o: main.c
	gcc -c main.c
getop.o: getop.c
	gcc -c getop.c
stack.o: stack.c
	gcc -c stack.c
getch.o: getch.c
	gcc -c getch.c
